apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: rishavsarkar122/ai-hospital-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: "production"
            - name: DATABASE_URL
              value: "postgresql+psycopg://hospital:your_secure_password@postgres:5432/hospital_command_center"
            - name: SECRET_KEY
              value: "your_secret_key"
            - name: FRONTEND_URL
              value: "http://localhost:3000"
            - name: CORS_ORIGINS
              value: "http://localhost:3000"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
