'use client';

import { ArrowLeft, ArrowRight, Activity, Bed, BrainCircuit, ChevronRight, Clock3, Gauge, Hospital, Network, ShieldCheck, Users, Zap } from 'lucide-react';
import { useEffect } from 'react';

const wingData: Record<string, { label: string; short: string; tone: string; value: string; patients: string; beds: string; staff: string; queue: string; detail: string }> = {
  emergency: { label: 'Emergency wing', short: 'ED', tone: 'high', value: '81%', patients: '142', beds: '18', staff: '68%', queue: '14 min', detail: 'Arrival velocity is 15% above baseline. Triage is the next predicted constraint.' },
  icu: { label: 'Critical care wing', short: 'ICU', tone: 'critical', value: '94%', patients: '42', beds: '3', staff: '52%', queue: '9 min', detail: 'Capacity threshold is approaching. Reserve beds and prepare ventilators for the evening window.' },
  surgery: { label: 'Surgical wing', short: 'OR', tone: 'moderate', value: '68%', patients: '26', beds: '21', staff: '74%', queue: '22 min', detail: 'Turnover is stable. Three low-priority procedures can be flexed if pressure increases.' },
  radiology: { label: 'Imaging wing', short: 'RAD', tone: 'normal', value: '57%', patients: '81', beds: '12', staff: '88%', queue: '14 min', detail: 'Imaging capacity is healthy with strong staff coverage and a stable queue.' },
  ward: { label: 'General ward wing', short: 'WARD', tone: 'moderate', value: '76%', patients: '318', beds: '47', staff: '71%', queue: '18 min', detail: 'Discharge velocity is slightly below target. Step-down capacity is available for overflow.' },
  pediatrics: { label: 'Pediatric wing', short: 'PEDS', tone: 'normal', value: '48%', patients: '63', beds: '29', staff: '91%', queue: '8 min', detail: 'Pediatric operations are stable with low predicted risk over the next 12 hours.' },
};
const wingOrder = ['emergency', 'icu', 'surgery', 'radiology', 'ward', 'pediatrics'];

export function WingWorkspace({ departmentId, view }: { departmentId: string; view: string }) {
  const wing = wingData[departmentId] || wingData.icu;
  const flowView = view === 'flow';
  const navigate = (id: string, nextView = 'workspace') => { window.location.href = `/digital-twin?wing=${id}&view=${nextView}`; };
  useEffect(() => {
    const handleWorkspaceAction = (event: MouseEvent) => {
      const button = (event.target as HTMLElement).closest('button');
      const label = button?.textContent || '';
      if (label.includes('Send action for review')) navigate(departmentId, 'review');
      if (label.includes('Open department report')) navigate(departmentId, 'report');
    };
    document.addEventListener('click', handleWorkspaceAction);
    return () => document.removeEventListener('click', handleWorkspaceAction);
  }, [departmentId]);
  if (view === 'review') return <ReviewQueue wing={wing} navigate={navigate} />;
  if (view === 'report') return <DepartmentReport wing={wing} navigate={navigate} />;
  return <div className="wing-workspace-page">
    <div className="wing-workspace-head"><div><button className="back-link" onClick={() => { window.location.href = '/digital-twin'; }}><ArrowLeft size={15} /> Back to digital twin</button><span className="eyebrow">Department wing workspace / {wing.short}</span><h1>{wing.label}</h1><p>Live operational workspace for capacity, patient flow, and human-reviewed decisions.</p></div><span className={`workspace-status ${wing.tone}`}><i /> Live telemetry</span></div>
    <div className="wing-switcher">{wingOrder.map((id) => <button key={id} className={id === departmentId ? 'selected' : ''} onClick={() => navigate(id, view)}><strong>{wingData[id].short}</strong><span>{wingData[id].label.replace(' wing', '')}</span><b>{wingData[id].value}</b></button>)}</div>
    <div className="workspace-tabs"><button className={!flowView ? 'selected' : ''} onClick={() => navigate(departmentId, 'workspace')}><Gauge size={15} /> Wing workspace</button><button className={flowView ? 'selected' : ''} onClick={() => navigate(departmentId, 'flow')}><Network size={15} /> Patient flow graph</button></div>
    <div className="workspace-grid"><section className="panel wing-hero-panel"><div className="workspace-panel-head"><div><span className="eyebrow">{flowView ? 'Flow intelligence' : 'Operational state'}</span><h2>{flowView ? 'Patient flow graph' : 'Wing command view'}</h2></div><span className="workspace-node">NODE / {wing.short}-04</span></div>{flowView ? <div className="patient-flow-graph"><div className="flow-column"><FlowNode label="Arrival" value={wing.short === 'ED' ? '142' : '36'} tone="normal" /><FlowNode label="Assessment" value="24" tone="moderate" /></div><div className="flow-connector"><i /><i /><i /></div><div className="flow-column"><FlowNode label="In care" value={wing.patients} tone={wing.tone} /><FlowNode label="Observation" value="18" tone="normal" /></div><div className="flow-connector"><i /><i /><i /></div><div className="flow-column"><FlowNode label="Transfer / discharge" value={wing.beds} tone="normal" /></div></div> : <div className="workspace-signal"><div className={`signal-ring ${wing.tone}`}><strong>{wing.value}</strong><span>occupancy</span></div><div className="signal-copy"><div><strong>Pressure profile</strong><span>{wing.detail}</span></div><div className="signal-bars">{[38, 52, 47, 64, 58, 72, 68, 86, 78, 94].map((height, i) => <i key={i} style={{ height: `${height}%` }} className={i > 7 ? 'hot' : ''} />)}</div><small><i /> Demand signal updated 18 seconds ago</small></div></div>}<div className="flow-footer"><span><i className="green" /> Stable telemetry</span><span><i className="purple" /> AI signal active</span><span><Clock3 size={13} /> Next update 42 sec</span></div></section><aside className="panel workspace-insight"><div className={`workspace-risk ${wing.tone}`}><span>Current risk</span><strong>{wing.tone === 'critical' ? 'Critical' : wing.tone === 'high' ? 'High load' : wing.tone === 'moderate' ? 'Moderate' : 'Normal'}</strong></div><h2>{flowView ? 'Flow checkpoints' : 'Wing metrics'}</h2><div className="workspace-metrics"><div><Users size={16} /><strong>{wing.patients}</strong><span>Patients</span></div><div><Bed size={16} /><strong>{wing.beds}</strong><span>Available beds</span></div><div><Activity size={16} /><strong>{wing.staff}</strong><span>Staff capacity</span></div><div><Zap size={16} /><strong>{wing.queue}</strong><span>Median queue</span></div></div><div className="workspace-ai"><BrainCircuit size={18} /><div><strong>Explainable AI signal</strong><span>{wing.detail}</span></div></div><button className="primary-button wide"><ShieldCheck size={15} /> Send action for review <ArrowRight size={15} /></button><button className="secondary-button wide"><Hospital size={15} /> Open department report</button></aside></div>
    <div className="workspace-footer"><div><ShieldCheck size={16} /><span>Decision-support workspace. Operational actions require authorized human review.</span></div><span>Northstar Medical Center / {wing.short}</span></div>
  </div>;
}
function FlowNode({ label, value, tone }: { label: string; value: string; tone: string }) { return <div className={`flow-node ${tone}`}><span>{label}</span><strong>{value}</strong><small>patients</small></div>; }

function ReviewQueue({ wing, navigate }: { wing: typeof wingData.icu; navigate: (id: string, view?: string) => void }) {
  return <div className="wing-workspace-page action-page"><button className="back-link" onClick={() => navigate(Object.keys(wingData).find((id) => wingData[id] === wing) || 'icu')}><ArrowLeft size={15} /> Back to {wing.short} workspace</button><div className="action-page-header"><div><span className="eyebrow">Human approval queue / {wing.short}</span><h1>Send action for review</h1><p>Review the operational recommendation before it enters the authorized decision queue.</p></div><span className="review-badge"><ShieldCheck size={15} /> Awaiting review</span></div><div className="action-grid"><section className="panel action-main"><div className="action-title"><div className="action-icon purple"><BrainCircuit size={20} /></div><div><span>AI-generated recommendation</span><h2>Protect {wing.label.toLowerCase()} capacity</h2></div></div><p>{wing.detail}</p><div className="action-factors"><strong>Why this action?</strong><span><Activity size={14} /> Demand signal rising ahead of the evening window</span><span><Bed size={14} /> {wing.beds} beds currently available</span><span><Users size={14} /> Staff capacity currently at {wing.staff}</span></div><div className="action-form"><label>Reviewer note<textarea placeholder="Add context for the approving team..." /></label><label>Review priority<select><option>High priority</option><option>Standard review</option><option>Monitor only</option></select></label></div><div className="card-actions"><button className="secondary-button" onClick={() => navigate(Object.keys(wingData).find((id) => wingData[id] === wing) || 'icu')}>Cancel</button><button className="primary-button" onClick={() => window.alert('Action added to the authorized review queue.')}><ShieldCheck size={15} /> Add to review queue</button></div></section><aside className="panel action-side"><span className="eyebrow">Approval guardrails</span><h2>Human review required</h2><p>This recommendation will not change beds, staffing, or equipment automatically.</p><div className="guardrail"><ShieldCheck size={17} /><span>Auditable decision record</span></div><div className="guardrail"><Clock3 size={17} /><span>Review SLA: 15 minutes</span></div><div className="guardrail"><Hospital size={17} /><span>Scope: {wing.label}</span></div></aside></div></div>;
}

function DepartmentReport({ wing, navigate }: { wing: typeof wingData.icu; navigate: (id: string, view?: string) => void }) {
  return <div className="wing-workspace-page action-page"><button className="back-link" onClick={() => navigate(Object.keys(wingData).find((id) => wingData[id] === wing) || 'icu')}><ArrowLeft size={15} /> Back to {wing.short} workspace</button><div className="action-page-header"><div><span className="eyebrow">Operations report / {wing.short}</span><h1>{wing.label} report</h1><p>Current performance, capacity signals, and forecast context for authorized hospital staff.</p></div><button className="secondary-button"><ArrowRight size={15} /> Export report</button></div><div className="report-kpis"><div><span>Occupancy</span><strong>{wing.value}</strong><small>+6% since 6 AM</small></div><div><span>Patients in care</span><strong>{wing.patients}</strong><small>Live census</small></div><div><span>Available beds</span><strong>{wing.beds}</strong><small>Ready for allocation</small></div><div><span>Median queue</span><strong>{wing.queue}</strong><small>-3 min today</small></div></div><div className="action-grid"><section className="panel report-chart"><div className="section-title"><div><h2>Wing performance signal</h2><span>Last 12 hours / live telemetry</span></div><span className="report-updated"><i /> Updated now</span></div><div className="report-bars">{[34,44,38,51,46,59,55,67,62,74,70,82].map((height, index) => <div key={index}><i style={{ height: `${height}%` }} /><span>{index + 1}h</span></div>)}</div></section><aside className="panel report-side"><span className="eyebrow">AI summary</span><h2>Pressure is {wing.tone === 'critical' ? 'approaching threshold' : 'within monitored range'}.</h2><p>{wing.detail}</p><button className="primary-button wide" onClick={() => navigate(Object.keys(wingData).find((id) => wingData[id] === wing) || 'icu', 'review')}>Review recommended action <ArrowRight size={15} /></button></aside></div></div>;
}
